lsnum1 = input("Enter the 1 st number\n")
num1 = int(num1)
print(num1)
num2 = input("Enter the 2nd number\n")
num2 = int(num2)
print(num2)
print(num1+num2)
print(num1-num2)
print(num1*num2)
print(num1/num2)

print(type(num1))